### ISSUE TITLE
Question about pybind11 and linking

### ISSUE THREAD

**Issue by petrasvestartas** [compas-dev/compas_cgal#13]
Hi @brgcode ,

Thank you for a help during the visit in Zurich.

**Short description what I did:**
I went through **compas_cgal** in order to replicate the workflow by my code without installing this repo, simply by learning from the files that are uploaded here. I managed to run the slicer from C++ in **compas_wood** - new empty environment you helped to create.

**My current workflow:**
1) I set up a Visual Studio 2019 project that links pybind11, CGAL, boost and eigen.
Compiles without issues.
2) Then I added 4 files in **compas_wood**  with a more or less similar code to original repo:
     slicer.py
     slicer.pyi
     types.py
     test_slicer.py
[CGAL.zip](https://github.com/compas-dev/compas_cgal/files/7106506/CGAL.zip)

3) Lastly I tested tect_slicer.py and I get a result of 338 polylines, which I assume is correct and verifies that C++ and CPython talks to each other:
![image](https://user-images.githubusercontent.com/18013985/132030248-ad0a4641-27d2-4e0e-950f-61beffd45ad6.png)

**Question:**
How do you link C++ Python binding directly in VS Code because I have to write following path which I assume is different on every computer and depending on operating system these bindings must be compiled differently on each machine:

I know that this can be difficult to explain, but I need this to move forward and depending on your time I could come to Zurich if needed.

```
import sys
folder = "C:/IBOIS57/_Code/Software/Python/Pybind11Example/vsstudio/Release/"
if folder not in sys.path:
    sys.path.append(folder)
import pybind11module
```

In my case I have a Visual Studio 2019 project that helps to debug the code, link libraries and build pybind11module.cp38-win_amd64.pyd file:
![image](https://user-images.githubusercontent.com/18013985/132018994-1cc8c9d1-112a-4b30-a502-b543f37436f3.png)

```

import numpy as np
from compas.plugins import plugin

#Import module from folder instead of using -> from _cgal import slicer

import sys
folder = "C:/IBOIS57/_Code/Software/Python/Pybind11Example/vsstudio/Release/"
if folder not in sys.path:
    sys.path.append(folder)
import pybind11module


@plugin(category='trimesh', pluggable_name='trimesh_slice')
def slice_meshPython(mesh, planes):
    """Slice a mesh by a list of planes.
    Parameters
    ----------
    mesh : tuple of vertices and faces
        The mesh to slice.
    planes : list of (point, normal) tuples or compas.geometry.Plane
        The slicing planes.
    Returns
    -------
    list of arrays
        The points defining the slice polylines.
    """
    vertices, faces = mesh
    points, normals = zip(*planes)
    V = np.asarray(vertices, dtype=np.float64)
    F = np.asarray(faces, dtype=np.int32)
    P = np.array(points, dtype=np.float64)
    N = np.array(normals, dtype=np.float64)

    pybind11module.say_hello()
    pointsets = pybind11module.slicerCGAL.slice_meshCGAL(V, F, P, N)
    return pointsets



```

![image](https://user-images.githubusercontent.com/18013985/132019846-bd52b00b-99c7-4768-ab8f-1730e69c30ed.png)

**Comment by brgcode** [comment]
information about the pybind11 build systems is available here https://pybind11.readthedocs.io/en/stable/compiling.html#

`compas_cgal` uses the setuptools version.

you should be able to do the following
```bash
conda create -n cgal python=3.8 eigen=3.3 boost-cpp cgal-cpp">=5.0" mpir mpfr pybind11 compas --yes
conda activate cgal
cd compas_cgal
pip install -e .
```

this should compile the c++ code and install an editable version of the python wrapper in your environment, which is then directly available to Python.

once you want to distribute this to others, ideally you add a `conda` recipe and push this to `conda-forge`...

**Comment by brgcode** [comment]
the above will always compile "everything". if you just want to compile one module, you can change the list of extension modules in `setup.py`
```python
ext_modules = [
    Extension(
        'compas_cgal._cgal',
        sorted([
            'src/compas_cgal.cpp',
            'src/compas.cpp',
            'src/meshing.cpp',
            'src/booleans.cpp',
            'src/slicer.cpp',
            'src/intersections.cpp',
            'src/measure.cpp',
        ]),
        include_dirs=[
            './include',
            get_eigen_include(),
            get_pybind_include()
        ],
        library_dirs=[
            get_library_dirs(),
        ],
        libraries=['mpfr', 'gmp'],
        language='c++'
    ),
]

```

**Comment by petrasvestartas** [comment]
Thank you for an answer, I am trying to understand this.
To make things less breakable, I just want to gradually modify the current compas_cgal and add parts of new code.

If I understand correctly, I have to install conda environment, then I can modify the code of C++ directly in VS code?

In Anaconda prompt I typed:
conda create -n cgal python=3.8 eigen=3.3 boost-cpp cgal-cpp">=5.0" mpir mpfr ```
pybind11 compas --yes
conda activate cgal

```
But after this breaks. Which directory contains that setup.py file?

```
cd compas_cgal
pip install -e .
```

![image](https://user-images.githubusercontent.com/18013985/132214515-8d313341-da59-481e-882e-ff99f435e3f3.png)

**Comment by brgcode** [comment]
you seem to be working in the `cgal` environment folder.

the `setup.py` i am referring to is part of the `compas_cgal` repo. you should issue the command `pip install -e .` from there.

once you have managed to build `compas_cgal` locally as described above, you can try doing the same from `compas_wood`, or whichever package you're experimenting with...

**Comment by petrasvestartas** [comment]
Dear @brgcode ,

I am coming back to this issue, since I a bit more confident that my code works and changing from opennurbs to cgal was a bit of a learning curve. All good for now. I would like to ask again help considering package creation and pushing it outside my pc.
Again I am replicating steps:

I did this:
1. conda create -n compas_cgal python=3.8 eigen=3.3 boost-cpp cgal-cpp">=5.0" mpir mpfr pybind11 compas --yes
![image](https://user-images.githubusercontent.com/18013985/144122800-fff5c266-0a20-4014-ba52-75a95528477e.png)

2. This time I have compas_cgal installed, not cgal. I activate compas_cgal:
![image](https://user-images.githubusercontent.com/18013985/144122915-9039ae66-e01e-403b-a23d-68755cfe69c7.png)

3. But I did not managed go to compas_cgal folder. But I am at least in compas_cgal environment. So I tried command `pip install -e .` This complains that I am in a wrong directory and setup.py is not here. 
![image](https://user-images.githubusercontent.com/18013985/144123962-e522c7a1-b4c2-41bb-9b3f-1cac13a7a413.png)

4. I searched where the setup.py could be in my pc. 
Should I run this file?

![image](https://user-images.githubusercontent.com/18013985/144124089-a17f2308-9691-47f6-a4a0-dd02e2571648.png)

**Comment by brgcode** [comment]
it is not clear to me what you are trying to accomplish. i assume you already have a setup that allows you to locally build your code and use it. as a next step, i assume you want to release `compas_wood`?

if that is the case, i have the feeling you are mixing up a few things, since all of the steps you are performing should be done in your development environment, for examples named `cgal` (but in your case it would make more sense to call it `wood`), from the `compas_wood` repo. the folders in the anaconda `env` directory serve a different purpose and are never involved in this process.

in a nutshell, the proces would be the following

```bash
conda create -n wood-dev -c conda-forge python=3.8 mpir mpfr boost-cpp eigen=3.3 cgal-cpp=5.3 pybind11 compas compas_view2 --yes
conda activate wood-dev
conda install cookiecutter
cd path/to/dir/where/you/keep/your/repos
cookiecutter gh:compas-dev/tpl-extension
```

cookiecutter will ask you a bunch of questions about your package. once this is done, proceed with the following (i am going to assume you named the package `compas_wood`)

```bash
cd compas_wood
git add .
git commit -m "Initial commit."
pip install -r requirements-dev.txt
```

update the repo with you code. and update the `setup.py` file of the repo similar to the one found in `compas_cgal`. if there are no bugs in your code and everything is properly linked, every subsequent call to the `pip` installer will compile your repo making the code available as part of your editable install.

```bash
pip install -e .
```

there is not much more to it than that. as you can see everything happens from within your local repo...

once you have a stable version, you can consider making this available to others via `conda-forge`. for this you would have to write a `conda` recipe, but since most of the installation process is handled by `setup.py` that should be relatively straightforward...

**Comment by petrasvestartas** [comment]
Hi @brgcode ,

Thanks for the patience on this issue.

`it is not clear to me what you are trying to accomplish. i assume you already have a setup that allows you to locally build your code and use it. as a next step, i assume you want to release compas_wood?`
I have the same repo as installed with you. I was loading .pyd module that was built using Visual Studio.
Now I want to build compas_wood locally.

I followed what you described:
1. Place all C++ source files here:
https://github.com/ibois-epfl/compas_wood/tree/main/src

2. I changed setup according to compas_cgal
https://github.com/ibois-epfl/compas_wood/blob/main/setup.py

3. After`  pip install -e .` in directory of C:\Users\petra\compas_wood
I get following errors and trying to understand how to make them go away
![image](https://user-images.githubusercontent.com/18013985/144584421-b5479f17-b0f6-4967-b3ad-c468cb33248e.png)

All the code is already here https://github.com/ibois-epfl/compas_wood. And if I succeed with this stuff, I would like to push to conda-forge.

**Comment by brgcode** [comment]
okay  i will have a look at the repo and send a PR

**Comment by petrasvestartas** [comment]
Thank you

**Comment by petrasvestartas** [comment]
Hi @brgcode ,

Maybe you had time to look at my code?
Or maybe you know what linking issue regarding the last post I have?

**Comment by brgcode** [comment]
sorry, have not had time yet. will try to get to it later this week...

**Comment by petrasvestartas** [comment]
Dear @brgcode ,

Maybe you have time to look at this issue this week?

If you are too busy, maybe you could explain how linking works when compiling on a local machine? Does a user need to download all the c++ header only libraries or iis it somehow done automatically?

**Comment by brgcode** [comment]
if the compiler can't find `Eigen` it is probably because you have not installed it in your development environment. if `Eigen` is installed in your environment, the `get_eigen_include` function in `setup.py` will find it.

i noticed that your repo is a bit all over the place. for example, you have two calls to `setup` in `setup.py`. therefore i would suggest to do a bit of cleaning up first, then create a fresh development env, with all requirements properly installed, and then follow the step-by-step instructions again.

before testing your dev environment on `compas_wood`, try building `compas_cgal` first, as a sanity check, since they have the same requirements. if it works for `compas_cgal` it should work for your lib as well, so then you at least already now that is not the cause of your errors.

the dev instructions for `compas_cgal` are quite precise. just follow them to the letter...

**Comment by brgcode** [comment]
they are in the include dir a few lines further down...

**Comment by petrasvestartas** [comment]
Thank you

It compiles:
![image](https://user-images.githubusercontent.com/18013985/146331230-5b062c80-2be8-4720-8bef-c2e903983c73.png)

The following question is about functions calls.

Do you wrap function in .pyi files? Like this:
![image](https://user-images.githubusercontent.com/18013985/146331649-200e9542-eea6-4c7a-82d3-123d990847b8.png)

And call this functions using plugins import? Like this:
![image](https://user-images.githubusercontent.com/18013985/146331802-902d54b9-193a-4a1f-876b-7f4e90682c3d.png)

Are there any other steps needed?
I am trying to call simple print function, which is not found currently.

**Comment by brgcode** [comment]
no, the `*.pyi` files are type stubs. they contain typing information for static type checkers like `mypy` and `pylance`. you can ignore those. they are not strictly needed. they are a bit like header files in c++. they don't contain any implementations.

the wrapper functions are in the regular `*.py` files...

**Comment by brgcode** [comment]
using the plugin functionality only makes sense if there are corresponding pluggables in the core compas framework. so in your case you can leave this out entirely. just make normal wrapper functions that convert the input data to numpy and hand it over to the c++ implementation.

**Comment by petrasvestartas** [comment]
Thanks.

Sorry to bother again. It seems I still have issues within the building part "pip install -e ." because the .pyd file are 0 byte in size, meaning the building failed. I was mistaken by typing consequently two times  "pip install -e ."

Is there any pip command that deletes previous files similar to visual studio "rebuild" command?
Currently I am manually deleting `_cgal.cp38-win_amd64.pyd` file each time.

The building error message does not say much, but it probably means that the compiler does not find .cpp files:
![image](https://user-images.githubusercontent.com/18013985/146345486-fa72bf57-7909-45c2-bf62-2f8b1fc8f9e2.png)
![image](https://user-images.githubusercontent.com/18013985/146346921-143238de-6062-48c1-9dc2-e1a9fb0f5915.png)

**Comment by brgcode** [comment]
you should not even have a `_cgal....pyd` file. this is something created by `compas_cgal` and has nothing to do with `compas_wood`...

i am not trying to be mean, but i find the current process completely counter-productive.

i don't understand why you are trying to rush through this. in my opinion, with a step-by-step process this would have been solved ages ago. why not make a clean repo and first get the basics right before adding all your code to it?!

i keep pointing at the `compas_cgal` repo as a good example to start from because everything is nicely separated and easy to follow. i can't find any of this logic in your current code structure. there are also many parts of the code that are clearly the result of a quick copy-paste and were never properly adapted. other things seem completely missing. for example, and i might be wrong, but as far as i can tell, the `pybind11.h` headers are never included.

so, the best advice i can give you is to start from scratch with a clean repo and do things step by step so you can figure out where your process goes wrong. starting with a hello function is a good idea, but then do ONLY that first, without having 100 other things going on that could be influencing things. once that works you can start moving stuff back in...

**Comment by petrasvestartas** [comment]
Finally builds and runs...

Today, I went through this pybind11 example https://github.com/pybind/python_example/blob/master/setup.py
and gradually learnt the differences between that simple one and the cgal package. I know they are using different build methods but I found the naming issues I had in .cpp files.

The pybind11 headers were correct, just I do not place them in compas.h but in xxx_interop_python.h

Then I tested basic hello world and eventually the function I wrapped before:
![image](https://user-images.githubusercontent.com/18013985/146581155-a0520cd5-2cad-4f8b-8995-1fee3b07e510.png)

And I the methods works fine, and I get the display as before:
![image](https://user-images.githubusercontent.com/18013985/146581428-23dfc9e1-647e-4612-93d3-362f8d17c31e.png)

I believe, I was very intimidated by a lot of options in setup file,
and yes, rewriting step by step instead of copy-paste helped a lot.
Thanks for your help.

I would like also to try my code on my mac to see if it works correctly.
And I also have to learn how to use compas-forge.

**Comment by brgcode** [comment]
nice!
good for you...

for mac, make sure to use the correct dependencies. there are some differences between windows and mac. again, look at the readme of `compas_cgal`.

`conda-forge` is easy if things already work locally...

**Comment by petrasvestartas** [comment]
It works on Mac:
<img width="1440" alt="Screenshot 2021-12-23 at 11 15 11" src="https://user-images.githubusercontent.com/18013985/147225831-073e8ec9-5cee-4c73-924b-fa43748f4795.png">

GCC compiler is a bit different than on windows, I had to adapt a little bit C++ code that it works on both os. 

Could you an advice/link to tutorials how to upload my repo to condo-forge?
I never used it.

**Comment by brgcode** [comment]
this seems solved...
